RESTAURANT_CATEGORIES = [
  "Food Quality",
  "Pricing",
  "Ambiance",
  "Location",
  "Menu Variety",
  "Cleanliness",
  "Reservation",
  "Parking",
  "Beverages",
  "Payment Options",
  "Noise Level",
  "Takeout/Delivery",
  "Allergies/Accommodations",
  "Service",
  "Serving Time",
  "Staff",
  "Customer Experience",
  "Health & Safety",
  "Value Proposition",
  "Feedback Channels",
  "Others"
].freeze

HOTEL_CATEGORIES = [
  "Check-In/Check-Out",
  "Amenities",
  "Ambiance",
  "Cleanliness",
  "Location",
  "Room Comfort",
  "Service",
  "Pricing",
  "Food and Dining",
  "Parking",
  "Wi-Fi/Technology",
  "Security",
  "Sustainability",
  "Accessibility",
  "Booking/Reservation",
  "Staff",
  "Customer Experience",
  "Health & Safety",
  "Value Proposition",
  "Feedback Channels",
  "Others"
]